CREATE TABLE PIZARRAS_PUBLICAS (
  FECHA        DATE         NOT NULL,
  PLAZA        VARCHAR2(50) NOT NULL,
  FUENTE       VARCHAR2(50) NOT NULL,
  PRODUCTO     VARCHAR2(30) NOT NULL,
  MONEDA       VARCHAR2(10) DEFAULT 'ARS' NOT NULL,
  PRECIO_TN    NUMBER(15,2) NOT NULL,
  VAR_ABS      NUMBER(15,2),
  VAR_PCT      NUMBER(9,4),
  TENDENCIA    VARCHAR2(5),
  HORA_FUENTE  VARCHAR2(5),
  URL_FUENTE   VARCHAR2(400),
  CONSTRAINT PK_PIZARRAS PRIMARY KEY (FECHA, PLAZA, FUENTE, PRODUCTO)
);
CREATE INDEX IDX_PIZARRAS_FECHA ON PIZARRAS_PUBLICAS(FECHA);
CREATE INDEX IDX_PIZARRAS_PRODUCTO ON PIZARRAS_PUBLICAS(PRODUCTO);
