name: Build & Deploy API (Docker → Azure Web App)

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/pizarras-api:latest" >> $GITHUB_OUTPUT

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.IMAGE }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart \
              --name ${{ secrets.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
