name: Daily scrape to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '15 12 * * *'  # 12:15 UTC

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: app
      SCRAPER_DRIVER: playwright
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show runner info
        shell: bash
        run: |
          set -euxo pipefail
          uname -a || true
          command -v python3
          python3 --version
          python3 -m pip --version || true
          ls -la

      - name: Install deps (sin oracledb)
        shell: bash
        run: |
          set -euxo pipefail
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install \
            fastapi==0.115.6 \
            requests==2.32.3 \
            beautifulsoup4==4.12.3 \
            lxml==5.2.2 \
            html5lib==1.1 \
            pandas==2.2.2 \
            playwright==1.55.0
          python3 -m playwright install chromium

      - name: Make index.html
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p public
          cat > public/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Pizarras cache</title>
          <h1>Pizarras cache (GitHub Pages)</h1>
          <ul>
            <li><a href="cotizaciones_rosario.json">cotizaciones_rosario.json</a></li>
            <li><a href="cotizaciones_bahia.json">cotizaciones_bahia.json</a></li>
            <li><a href="cotizaciones_cordoba.json">cotizaciones_cordoba.json</a></li>
            <li><a href="cotizaciones_quequen.json">cotizaciones_quequen.json</a></li>
            <li><a href="cotizaciones_darsena.json">cotizaciones_darsena.json</a></li>
            <li><a href="cotizaciones_locales.json">cotizaciones_locales.json</a></li>
          </ul>
          HTML

      - name: Run scraper (Playwright)
        shell: bash
        env:
          SCRAPER_DRIVER: playwright
        run: |
          set -euxo pipefail
          source .venv/bin/activate
          python3 - <<'PY'
          import os, sys, json
          from pathlib import Path
          os.environ["SCRAPER_DRIVER"] = "playwright"
          sys.path.insert(0, "app")
          from main import cotizaciones

          def dump(plaza, only_base):
              data = cotizaciones(plaza, only_base)
              Path("public").mkdir(exist_ok=True)
              suf = "_base" if int(only_base)==1 else ""
              fn = f"public/cotizaciones_{data['plaza']}{suf}.json"
              with open(fn, "w", encoding="utf-8") as f:
                  json.dump(data, f, ensure_ascii=False)
              print(f"Wrote {fn} (items={len(data.get('items',[]))}, error={data.get('error')})")

          for plaza in ["rosario","bahia","cordoba","quequen","darsena","locales"]:
              dump(plaza, 1)
              dump(plaza, 0)
          print("OK")
          PY

      - name: Verify artifact contents
        shell: bash
        run: |
          set -euxo pipefail
          [ -d public ] || (echo "public/ no existe"; exit 1)
          find public -type f -maxdepth 2 -print
          # Falla si está vacía
          test -n "$(find public -type f -maxdepth 2 | head -n1)"

      # 👇 Paso nuevo: asegurar gtar en macOS self-hosted
      - name: Ensure gnu-tar (gtar)
        shell: bash
        run: |
          set -euxo pipefail
          # Forzar instalación en ARM nativo (Apple Silicon)
          if ! command -v gtar >/dev/null 2>&1; then
            arch -arm64 brew install gnu-tar
          fi
          # Mostrar versión para verificar
          gtar --version
          # (Opcional) Priorizar los shims gnubin en PATH (exponen 'tar' → gtar)
          echo "/opt/homebrew/opt/gnu-tar/libexec/gnubin" >> "$GITHUB_PATH"

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 Ajustarlo en basu a tu sugerencia de la opción A.
