name: Daily scrape to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '15 12 * * *'  # 12:15 UTC

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👇 Creamos un directorio temporal SIN espacios y copiamos el repo ahí
      - name: Make safe workspace
        shell: bash
        run: |
          SAFE="$RUNNER_TEMP/work"
          rm -rf "$SAFE"
          mkdir -p "$SAFE"
          rsync -a "$GITHUB_WORKSPACE"/ "$SAFE"/
          echo "SAFE_WORKSPACE=$SAFE" >> "$GITHUB_ENV"

      - name: Show runner info
        shell: bash
        working-directory: ${{ env.SAFE_WORKSPACE }}
        run: |
          uname -a || true
          command -v python3
          python3 --version
          command -v pip3 || true
          python3 -m pip --version || true
          ls -la

      - name: Install deps (sin oracledb)
        shell: bash
        working-directory: ${{ env.SAFE_WORKSPACE }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install \
            fastapi==0.115.6 \
            requests==2.32.3 \
            beautifulsoup4==4.12.3 \
            lxml==5.2.2 \
            html5lib==1.1 \
            pandas==2.2.2 \
            playwright==1.55.0
          # macOS self-hosted: sin --with-deps
          python3 -m playwright install chromium

      - name: Make index.html
        shell: bash
        working-directory: ${{ env.SAFE_WORKSPACE }}
        run: |
          mkdir -p public
          cat > public/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Pizarras cache</title>
          <h1>Pizarras cache (GitHub Pages)</h1>
          <ul>
            <li><a href="cotizaciones_rosario.json">cotizaciones_rosario.json</a></li>
            <li><a href="cotizaciones_bahia.json">cotizaciones_bahia.json</a></li>
            <li><a href="cotizaciones_cordoba.json">cotizaciones_cordoba.json</a></li>
            <li><a href="cotizaciones_quequen.json">cotizaciones_quequen.json</a></li>
            <li><a href="cotizaciones_darsena.json">cotizaciones_darsena.json</a></li>
            <li><a href="cotizaciones_locales.json">cotizaciones_locales.json</a></li>
          </ul>
          HTML

      - name: Run scraper (Playwright)
        env:
          SCRAPER_DRIVER: playwright
        shell: bash
        working-directory: ${{ env.SAFE_WORKSPACE }}
        run: |
          python3 - <<'PY'
          import os, sys, json
          from pathlib import Path
          os.environ["SCRAPER_DRIVER"] = "playwright"
          sys.path.insert(0, "app")   # tu código está en app/main.py
          from main import cotizaciones

          def dump(plaza, only_base):
              data = cotizaciones(plaza, only_base)
              Path("public").mkdir(exist_ok=True)
              suf = "_base" if int(only_base)==1 else ""
              fn = f"public/cotizaciones_{data['plaza']}{suf}.json"
              with open(fn, "w", encoding="utf-8") as f:
                  json.dump(data, f, ensure_ascii=False)
              print(f"Wrote {fn} (items={len(data.get('items',[]))}, error={data.get('error')})")

          for plaza in ["rosario","bahia","cordoba","quequen","darsena","locales"]:
              dump(plaza, 1)
              dump(plaza, 0)
          print("OK")
          PY

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.SAFE_WORKSPACE }}/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
