name: Diagnose ubuntu-latest reachability

on:
  workflow_dispatch:

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Curl sanity check
        run: |
          set -euxo pipefail
          URL="https://www.bolsadecereales.com/camara-arbitral"
          echo "1) curl default UA"
          curl -I -sS "$URL" || true
          echo "2) curl with browser-like UA"
          UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123 Safari/537.36"
          curl -I -sS -A "$UA" "$URL" || true

      - name: Setup Python + Playwright
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install playwright==1.55.0
          python -m playwright install chromium
          python -m playwright install-deps || true

      - name: Playwright fetch (Chromium) and report
        run: |
          set -euxo pipefail
          python - <<'PY'
          from playwright.sync_api import sync_playwright
          URL="https://www.bolsadecereales.com/camara-arbitral"
          with sync_playwright() as p:
              b = p.chromium.launch()
              ctx = b.new_context(user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123 Safari/537.36")
              page = ctx.new_page()
              resp = page.goto(URL, wait_until="domcontentloaded", timeout=30000)
              print("HTTP status:", resp.status if resp else "no response")
              print("Final URL:", page.url)
              print("Title:", page.title())
              html = page.content()
              print("HTML head:", html[:500].replace("\n"," "))
              b.close()
          PY
